COMMENT ON COLUMN tags.record_id IS 'OMS Generated Number';
COMMENT ON COLUMN tags.element_id IS 'NYI';
COMMENT ON COLUMN tags.element_name IS 'NYI';
COMMENT ON COLUMN tags.element IS 'NYI';
COMMENT ON COLUMN tags.phase IS 'From OMS Feature';
COMMENT ON COLUMN tags.shapefield IS 'From OMS Feature';
COMMENT ON COLUMN tags.lastmodifiedtime IS 'Time Tag was Modified';
COMMENT ON COLUMN tags.tag_status IS 'Current State of the Tag';
COMMENT ON COLUMN tags.temp_closable IS '''True'' if tag type is temp closeable';
COMMENT ON COLUMN tags.temp_closed IS 'Current state of the tag';
COMMENT ON COLUMN tags.closed IS 'Current state of the tag';
COMMENT ON COLUMN tags.tag_num IS 'Unique OMS generated number';
COMMENT ON COLUMN tags.created_by IS 'Current OMS user';
COMMENT ON COLUMN tags.modified_by IS 'Current OMS user';
COMMENT ON COLUMN tags.tag_type IS 'Selected from ''tag_type'' entries';
COMMENT ON COLUMN tags.requested_by IS 'Selected OMS User from combo box';
COMMENT ON COLUMN tags.truck IS 'Selected OMS Truck from combo box';
COMMENT ON COLUMN tags.requested_for IS 'Selected OMS User from combo box';
COMMENT ON COLUMN tags.purpose IS 'Selected from ''tag_purpose'' entries';
COMMENT ON COLUMN tags.equipment_type IS 'Selected from ''tag_equipment_type'' entries';
COMMENT ON COLUMN tags.pole_num_from IS 'From OMS feature';
COMMENT ON COLUMN tags.pole_num_to IS 'From OMS feature';
COMMENT ON COLUMN tags.released_by IS 'From OMS feature';
COMMENT ON COLUMN tags.notes IS 'User entered data';
COMMENT ON COLUMN tags.taglocation IS 'From OMS feature';
COMMENT ON COLUMN tags.created_date IS 'Date created';
COMMENT ON COLUMN tags.effective_date IS 'Date tag becomes effective';
COMMENT ON COLUMN tags.closed_date IS 'Date tag was closed';
COMMENT ON COLUMN tags.action_performed IS 'NEW, UPDATE, or DELETE for history';