COMMENT ON COLUMN tags_history.record_id IS 'OMS Generated Number';
COMMENT ON COLUMN tags_history.element_id IS 'NYI';
COMMENT ON COLUMN tags_history.element_name IS 'NYI';
COMMENT ON COLUMN tags_history.element IS 'NYI';
COMMENT ON COLUMN tags_history.phase IS 'From OMS Feature';
COMMENT ON COLUMN tags_history.shapefield IS 'From OMS Feature';
COMMENT ON COLUMN tags_history.lastmodifiedtime IS 'Time Tag was Modified';
COMMENT ON COLUMN tags_history.tag_status IS 'Current State of the Tag';
COMMENT ON COLUMN tags_history.temp_closable IS '''True'' if tag type is temp closeable';
COMMENT ON COLUMN tags_history.temp_closed IS 'Current state of the tag';
COMMENT ON COLUMN tags_history.closed IS 'Current state of the tag';
COMMENT ON COLUMN tags_history.tag_num IS 'Unique OMS generated number';
COMMENT ON COLUMN tags_history.created_by IS 'Current OMS user';
COMMENT ON COLUMN tags_history.modified_by IS 'Current OMS user';
COMMENT ON COLUMN tags_history.tag_type IS 'Selected from ''tag_type'' entries';
COMMENT ON COLUMN tags_history.requested_by IS 'Selected OMS User from combo box';
COMMENT ON COLUMN tags_history.truck IS 'Selected OMS Truck from combo box';
COMMENT ON COLUMN tags_history.requested_for IS 'Selected OMS User from combo box';
COMMENT ON COLUMN tags_history.purpose IS 'Selected from ''tag_purpose'' entries';
COMMENT ON COLUMN tags_history.equipment_type IS 'Selected from ''tag_equipment_type'' entries';
COMMENT ON COLUMN tags_history.pole_num_from IS 'From OMS feature';
COMMENT ON COLUMN tags_history.pole_num_to IS 'From OMS feature';
COMMENT ON COLUMN tags_history.released_by IS 'From OMS feature';
COMMENT ON COLUMN tags_history.notes IS 'User entered data';
COMMENT ON COLUMN tags_history.taglocation IS 'From OMS feature';
COMMENT ON COLUMN tags_history.created_date IS 'Date created';
COMMENT ON COLUMN tags_history.effective_date IS 'Date tag becomes effective';
COMMENT ON COLUMN tags_history.closed_date IS 'Date tag was closed';
COMMENT ON COLUMN tags_history.action_performed IS 'NEW, UPDATE, or DELETE for history';